# Generated by Django 4.0 on 2021-12-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_post_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='SOME STRING', null=True, upload_to=''),
        ),
    ]
